print('Bem vindo a histórica maluca')
print('Para criar a história me forneça o seguinte....')
f = input('Digite o nome de um famoso: ')
v = input('Digite um Verbo: ')
l = input('Digite um lugar: ')
n = int(input('Digite um número: '))
c = input('Digite uma cor: ')
o = input('Digite um objeto: ')
print(f'Um dia, no {l}, encontrei o(a) {f} segurando uma {o} {c}. Ele começou a {v} sem parar, e isso durou por {n} horas!')
